name: Build and Publish Docker Image

on:
    push:
        branches: [master]
    release:
        types: [published]

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tags
        id: image-tags
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/mosquitto-auth
          TAGS="latest"

          if [ "${{ github.event_name }}" == "release" ]; then
            VERSION_TAG=${{ github.event.release.tag_name }}
            TAGS="${TAGS} ${VERSION_TAG}"
          fi
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "TAGS=${TAGS}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref == 'refs/heads/master' && 'latest' || github.event.release.tag_name }}
